name: Build & Deploy Container App

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: nimoy-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DEPLOY_CLIENT_ID }}
          tenant-id: ${{ secrets.CI_TENANT_ID }}
          subscription-id: ${{ secrets.CI_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.DEPLOY_CLIENT_SECRET }}

      - name: Log in to Container Registry
        run: |
          docker login \
            ${{ secrets.CI_REGISTRY }} \
            -u ${{ secrets.CI_CLIENT_ID }} \
            -p ${{ secrets.CI_CLIENT_SECRET }}

      - name: Build & Push Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ secrets.CI_REGISTRY_IMAGE }}:$IMAGE_TAG .
          docker push ${{ secrets.CI_REGISTRY_IMAGE }}:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Update Azure Container App
        run: |
          az containerapp update \
            --name ${{ secrets.CI_CONTAINER_APP }} \
            --resource-group ${{ secrets.CI_RESOURCE_GROUP }} \
            --image ${{ secrets.CI_REGISTRY_IMAGE }}:${{ env.IMAGE_TAG }}
